### ISSUE TITLE
python client.py fails to run

### ISSUE THREAD

**Issue by notfood** [space-nuko/sd-model-manager#2]
Errors with:
```
Traceback (most recent call last):
  File "/media/Hakugyokurou/home/Projects/AI/sd-model-manager/client.py", line 99, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/media/Hakugyokurou/home/Projects/AI/sd-model-manager/client.py", line 87, in main
    server = await init_server()
  File "/media/Hakugyokurou/home/Projects/AI/sd-model-manager/client.py", line 45, in init_server
    host = server["config"].listen
  File "/media/Hakugyokurou/home/Projects/AI/ComfyUI/venv/lib/python3.10/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'config'
```

Fixed by changing `config` to `sdmm_config` in [client.py](https://github.com/space-nuko/sd-model-manager/blob/3f2c082/client.py#L45-L46) due to [main.py](https://github.com/space-nuko/sd-model-manager/blob/3f2c082/main.py#L34-L35) setting that value.

**Comment by ashun-kaede** [comment]
I have same issue about this. This fix method is worked. Thanks!
